### PR TITLE
External preset (general approach)

### PR DESCRIPTION
**Pull request by Foghrye4**
It's working in single-player. I need to test in in dedicated and remove unnecessary code inherited from previous versions.

### CODE REVIEW

**Comment by Niko-sk2x** [comment]
Looks mostly good. I'm not sire if the ATs are still needed, and I would like to also see a test of a preset with layers.

**Comment by Foghrye4** [comment]
Cleaned and checked with dedicated server. Multi-layer test added.

**Comment by Niko-sk2x** [comment]
Looks good. Is it ready to merge? (CI failed because of gradle, I have a fix ready)

**Comment by Foghrye4** [comment]
Yes.

**Pull request merged**
